"""Matrix-based sequence logos for standalone report cards and SVG exports.

Uses the differential report's A/C/G/T information-content rendering convention.
The embedding report provides its decoded ``payload``.
"""

MOTIF_LOGO_JAVASCRIPT = r'''
function motifLogoSvg(prefix,attrs=''){const counts=(payload.motif_matrices||{})[prefix];if(!Array.isArray(counts)||counts.length!==4||!Array.isArray(counts[0])||!counts[0].length||!counts.every(row=>Array.isArray(row)&&row.length===counts[0].length&&row.every(v=>typeof v==='number'&&Number.isFinite(v)&&v>=0)))return'';const width=420,height=150,bases=['A','C','G','T'],colors={A:'#198754',C:'#0d6efd',G:'#f59f00',T:'#dc3545'},left=46,right=14,top=16,bottom=32,plotW=width-left-right,plotH=height-top-bottom,npos=counts[0].length,colW=plotW/Math.max(1,npos),bits=[[],[],[],[]];for(let pos=0;pos<npos;pos++){let colSum=counts.reduce((acc,row)=>acc+(Number(row[pos])||0),0);if(Math.abs(colSum)<1e-12)colSum=1;const pfm=counts.map(row=>(Number(row[pos])||0)/colSum),entropy=-pfm.reduce((acc,p)=>acc+(p>0?p*Math.log2(Math.max(p,1e-12)):0),0),scale=Math.max(0,2-entropy);pfm.forEach((p,i)=>bits[i][pos]=p*scale)}const attr=attrs?` ${attrs}`:'',parts=[`<svg${attr} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img">`,`<rect width="100%" height="100%" fill="#ffffff"/>`,`<line x1="${left}" y1="${top+plotH}" x2="${left+plotW}" y2="${top+plotH}" stroke="#3b4552" stroke-width="1.2"/>`,`<line x1="${left}" y1="${top}" x2="${left}" y2="${top+plotH}" stroke="#3b4552" stroke-width="1.2"/>`,`<text x="18" y="${top+plotH/2}" transform="rotate(-90 18 ${top+plotH/2})" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="12" font-weight="700" fill="#152133">bits</text>`,`<text x="${left+plotW/2}" y="${height-7}" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="12" font-weight="700" fill="#152133">position</text>`];[0,1,2].forEach(tick=>{const y=top+plotH-(tick/2)*plotH;parts.push(`<line x1="${left-4}" y1="${y.toFixed(2)}" x2="${left}" y2="${y.toFixed(2)}" stroke="#3b4552" stroke-width="1"/>`,`<text x="${left-8}" y="${(y+4).toFixed(2)}" text-anchor="end" font-family="Arial,Helvetica,sans-serif" font-size="11" font-weight="700" fill="#56616f">${tick}</text>`)});for(let pos=0;pos<npos;pos++){let yCursor=top+plotH,order=[0,1,2,3].sort((a,b)=>bits[a][pos]-bits[b][pos]),xCenter=left+pos*colW+colW/2;if(npos<=18||pos===0||pos===npos-1||(pos+1)%5===0)parts.push(`<text x="${xCenter.toFixed(2)}" y="${top+plotH+13}" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="9" font-weight="700" fill="#56616f">${pos+1}</text>`);order.forEach(baseIdx=>{const value=bits[baseIdx][pos];if(value<=0.015)return;const letterH=Math.max(3,value/2*plotH);yCursor-=letterH;const base=bases[baseIdx],fontSize=Math.max(8,Math.min(40,letterH*1.25));parts.push(`<text x="${xCenter.toFixed(2)}" y="${(yCursor+letterH*.88).toFixed(2)}" text-anchor="middle" font-family="Arial Black,Arial,Helvetica,sans-serif" font-size="${fontSize.toFixed(2)}" font-weight="900" fill="${colors[base]}">${base}</text>`)})}parts.push('</svg>');return parts.join('')}
function motifLogoHtml(prefix){const svg=motifLogoSvg(prefix);if(svg)return svg;const logo=(payload.logos||{})[prefix]||{};return logo.svg||(logo.png?`<img alt="Motif logo" src="${logo.png}">`:'<span class="logo-empty">Motif logo unavailable</span>')}
function logoDataUri(prefix){const logo=(payload.logos||{})[prefix]||{},svg=motifLogoSvg(prefix)||logo.svg;return svg?'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg):(logo.png||'')}
'''
