#!/usr/bin/env python
"""De novo motif discovery preparation helpers."""

from __future__ import annotations

import argparse
import csv
import gzip
import html
import re
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

from Bio import SeqIO


@dataclass(frozen=True)
class CandidateSite:
    chrom: str
    start: int
    end: int
    name: str
    score: str = "."


def read_candidate_sites(path: str | Path) -> list[CandidateSite]:
    """Read BED or fp-tools candidate rows."""

    sites: list[CandidateSite] = []
    with Path(path).open(encoding="utf-8") as handle:
        for idx, line in enumerate(handle, start=1):
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue
            name = fields[3] if len(fields) > 3 and fields[3] else f"site_{idx}"
            score = fields[4] if len(fields) > 4 and fields[4] else "."
            sites.append(CandidateSite(fields[0], int(fields[1]), int(fields[2]), name, score))
    return sites


def load_genome_fasta(path: str | Path) -> dict[str, str]:
    """Load FASTA records into a chromosome-to-sequence dictionary."""

    fasta_path = Path(path)
    opener = gzip.open if fasta_path.suffix == ".gz" else open
    with opener(fasta_path, "rt", encoding="utf-8") as handle:
        return {record.id: str(record.seq).upper() for record in SeqIO.parse(handle, "fasta")}


def candidate_sequence(site: CandidateSite, genome: dict[str, str], flank: int = 0) -> tuple[str, str] | None:
    """Return a FASTA header and sequence for one candidate, clipped to chromosome bounds."""

    if site.chrom not in genome:
        return None
    chrom_seq = genome[site.chrom]
    center = int((site.start + site.end) / 2)
    half_width = max(0, int(flank))
    start = max(0, center - half_width) if half_width else max(0, site.start)
    end = min(len(chrom_seq), center + half_width) if half_width else min(len(chrom_seq), site.end)
    if end <= start:
        return None
    header = f"{site.name}|{site.chrom}:{start}-{end}|score={site.score}"
    return header, chrom_seq[start:end]


def export_candidate_fasta(candidates: str | Path, genome_fasta: str | Path, output: str | Path, flank: int = 0) -> int:
    """Export candidate-centered sequences to FASTA."""

    sites = read_candidate_sites(candidates)
    genome = load_genome_fasta(genome_fasta)
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with out_path.open("w", encoding="utf-8") as handle:
        for site in sites:
            result = candidate_sequence(site, genome, flank=flank)
            if result is None:
                continue
            header, sequence = result
            handle.write(f">{header}\n")
            for idx in range(0, len(sequence), 80):
                handle.write(sequence[idx:idx + 80] + "\n")
            written += 1
    return written


def discovery_motif_text(method: str, discovery_dir: str | Path) -> Path:
    """Return the MEME-format text output expected from an external discovery run."""

    if method == "dreme":
        filename = "dreme.txt"
    elif method == "streme":
        filename = "streme.txt"
    elif method == "meme":
        filename = "meme.txt"
    else:
        raise ValueError("method must be 'meme', 'dreme', or 'streme'")
    return Path(discovery_dir) / filename


def meme_command(fasta: str | Path, outdir: str | Path, method: str = "meme", extra_args: list[str] | None = None) -> list[str]:
    """Build an external MEME/DREME/STREME command without executing it."""

    if method not in {"meme", "dreme", "streme"}:
        raise ValueError("method must be 'meme', 'dreme', or 'streme'")
    if method == "streme":
        command = ["streme", "--p", str(fasta), "--oc", str(outdir)]
    else:
        command = [method, str(fasta), "-oc", str(outdir)]
    if extra_args:
        command.extend(extra_args)
    return command


def write_motif_discovery_plan(
    fasta: str | Path,
    outdir: str | Path,
    script: str | Path,
    method: str = "meme",
    known_motifs: str | Path | None = None,
    extra_args: list[str] | None = None,
) -> Path:
    """Write a reproducible shell script for MEME/DREME/STREME, Tomtom, and fp-tools summary."""

    outdir = Path(outdir)
    script = Path(script)
    script.parent.mkdir(parents=True, exist_ok=True)
    discovery_dir = outdir / method
    tomtom_dir = outdir / "tomtom"
    summary_tsv = outdir / "motif_summary.tsv"
    summary_html = outdir / "motif_summary.html"
    motif_txt = discovery_motif_text(method, discovery_dir)

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by fp-tools. Requires MEME Suite commands on PATH.",
        f"mkdir -p {shlex.quote(str(outdir))}",
        " ".join(shlex.quote(part) for part in meme_command(fasta, discovery_dir, method=method, extra_args=extra_args or [])),
    ]
    tomtom_tsv = ""
    if known_motifs is not None:
        lines.extend(
            [
                f"tomtom -oc {shlex.quote(str(tomtom_dir))} {shlex.quote(str(motif_txt))} {shlex.quote(str(known_motifs))}",
            ]
        )
        tomtom_tsv = f" --tomtom-tsv {shlex.quote(str(tomtom_dir / 'tomtom.tsv'))}"
    lines.append(
        f"motif-summary --meme-txt {shlex.quote(str(motif_txt))}{tomtom_tsv} "
        f"--out-tsv {shlex.quote(str(summary_tsv))} --out-html {shlex.quote(str(summary_html))}"
    )
    script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    script.chmod(0o755)
    return script



def parse_meme_txt(path: str | Path) -> list[dict[str, str | int | float | None]]:
    """Parse a compact motif summary from MEME text output."""

    motifs: list[dict[str, str | int | float | None]] = []
    current: dict[str, str | int | float | None] | None = None
    matrix_rows: list[list[float]] = []
    matrix_remaining = 0
    matrix_re = re.compile(r"w=\s*(\d+).*?nsites=\s*([0-9.eE+-]+).*?E=\s*([0-9.eE+-]+)")

    def finish_current() -> None:
        nonlocal current, matrix_rows, matrix_remaining
        if current is None:
            return
        if matrix_rows:
            alphabet = "ACGT"
            consensus = "".join(alphabet[int(max(range(len(row)), key=lambda idx: row[idx]))] for row in matrix_rows if len(row) >= 4)
            current["consensus"] = consensus
        motifs.append(current)
        current = None
        matrix_rows = []
        matrix_remaining = 0

    with Path(path).open(encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("MOTIF "):
                finish_current()
                parts = line.split(maxsplit=2)
                current = {
                    "source": "MEME",
                    "motif_id": parts[1] if len(parts) > 1 else "motif",
                    "alt_id": parts[2] if len(parts) > 2 else "",
                    "width": None,
                    "sites": None,
                    "e_value": None,
                    "q_value": None,
                    "consensus": "",
                    "target_id": "",
                    "p_value": None,
                }
                continue
            if current is None:
                continue
            if line.startswith("letter-probability matrix"):
                match = matrix_re.search(line)
                if match:
                    current["width"] = int(match.group(1))
                    current["sites"] = float(match.group(2))
                    current["e_value"] = float(match.group(3))
                    matrix_remaining = int(match.group(1))
                continue
            if matrix_remaining:
                values = [float(value) for value in line.split()[:4]]
                if len(values) == 4:
                    matrix_rows.append(values)
                    matrix_remaining -= 1
    finish_current()
    return motifs


def parse_tomtom_tsv(path: str | Path) -> list[dict[str, str | int | float | None]]:
    """Parse Tomtom TSV matches into a compact summary."""

    rows: list[dict[str, str | int | float | None]] = []
    with Path(path).open(encoding="utf-8") as handle:
        filtered = [line for line in handle if line.strip() and not line.startswith("#")]
    if not filtered:
        return rows
    reader = csv.DictReader(filtered, delimiter="\t")
    for row in reader:
        query = row.get("Query_ID") or row.get("Query ID") or row.get("query_id") or ""
        target = row.get("Target_ID") or row.get("Target ID") or row.get("target_id") or ""
        rows.append(
            {
                "source": "Tomtom",
                "motif_id": query,
                "alt_id": "",
                "width": int(row["Overlap"]) if row.get("Overlap") else None,
                "sites": None,
                "e_value": float(row["E-value"]) if row.get("E-value") else None,
                "q_value": float(row["q-value"]) if row.get("q-value") else None,
                "consensus": row.get("Query_consensus") or "",
                "target_id": target,
                "p_value": float(row["p-value"]) if row.get("p-value") else None,
            }
        )
    return rows


def summarize_motif_outputs(meme_txt: str | Path | None = None, tomtom_tsv: str | Path | None = None) -> list[dict[str, str | int | float | None]]:
    """Collect MEME and Tomtom motif summaries."""

    rows: list[dict[str, str | int | float | None]] = []
    if meme_txt:
        rows.extend(parse_meme_txt(meme_txt))
    if tomtom_tsv:
        rows.extend(parse_tomtom_tsv(tomtom_tsv))
    return rows


def write_motif_summary_tsv(rows: list[dict[str, str | int | float | None]], output: str | Path) -> None:
    columns = ["source", "motif_id", "alt_id", "target_id", "width", "sites", "p_value", "e_value", "q_value", "consensus"]
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, delimiter="\t", extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def consensus_logo_svg(consensus: str, height: int = 42) -> str:
    """Render a compact inline SVG consensus logo for HTML reports."""

    consensus = "".join(base for base in str(consensus).upper() if base in "ACGTN")
    if not consensus:
        return ""
    colors = {"A": "#2f9e44", "C": "#1971c2", "G": "#f08c00", "T": "#d6336c", "N": "#868e96"}
    width_per_base = 18
    width = max(width_per_base, len(consensus) * width_per_base)
    labels = []
    for idx, base in enumerate(consensus):
        x = idx * width_per_base + width_per_base / 2
        labels.append(
            f'<text x="{x:.1f}" y="{height - 10}" text-anchor="middle" '
            f'font-family="Arial, sans-serif" font-weight="700" font-size="22" '
            f'fill="{colors.get(base, colors["N"])}">{html.escape(base)}</text>'
        )
    return (
        f'<svg class="motif-logo" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-label="{html.escape(consensus)}">'
        f'<rect width="{width}" height="{height}" fill="#ffffff" />'
        f'{"".join(labels)}</svg>'
    )


def write_motif_summary_html(rows: list[dict[str, str | int | float | None]], output: str | Path, title: str = "fp-tools de novo motif summary") -> None:
    columns = ["source", "motif_id", "target_id", "width", "sites", "p_value", "e_value", "q_value", "consensus", "logo"]
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    escaped_title = html.escape(title)
    body_rows = []
    for row in rows:
        cells = []
        for column in columns:
            if column == "logo":
                cells.append(f"<td>{consensus_logo_svg(str(row.get('consensus') or ''))}</td>")
            else:
                cells.append(f"<td>{html.escape('' if row.get(column) is None else str(row.get(column)))}</td>")
        cells = "".join(cells)
        body_rows.append(f"<tr>{cells}</tr>")
    header = "".join(f"<th>{html.escape(column)}</th>" for column in columns)
    document = f"""<!doctype html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<title>{escaped_title}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 2rem; color: #1f2933; }}
table {{ border-collapse: collapse; width: 100%; table-layout: fixed; }}
th, td {{ border: 1px solid #d0d7de; padding: 0.45rem; text-align: left; vertical-align: top; word-wrap: break-word; }}
th {{ background: #f6f8fa; }}
.caption {{ color: #52616b; margin-bottom: 1rem; }}
.motif-logo {{ max-width: 100%; height: auto; }}
</style>
</head>
<body>
<h1>{escaped_title}</h1>
<p class=\"caption\">Parsed {len(rows)} MEME/Tomtom motif rows for downstream review and manuscript tables.</p>
<table>
<thead><tr>{header}</tr></thead>
<tbody>
{chr(10).join(body_rows)}
</tbody>
</table>
</body>
</html>
"""
    out_path.write_text(document, encoding="utf-8")

def export_fasta_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export candidate site sequences to FASTA for de novo motif discovery.")
    parser.add_argument("--candidates", required=True, help="BED or fp-tools candidate table.")
    parser.add_argument("--genome", required=True, help="Genome FASTA.")
    parser.add_argument("--out", required=True, help="Output FASTA path.")
    parser.add_argument("--flank", type=int, default=0, help="If >0, export +/- flank bp around the candidate center instead of exact BED intervals.")
    args = parser.parse_args(argv)

    written = export_candidate_fasta(args.candidates, args.genome, args.out, flank=args.flank)
    print(f"Wrote {written} sequences to {args.out}")
    return 0


def meme_command_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Print a MEME/DREME/STREME command for exported candidate FASTA.")
    parser.add_argument("--fasta", required=True, help="Existing candidate FASTA.")
    parser.add_argument("--outdir", required=True, help="External motif discovery output directory.")
    parser.add_argument("--method", choices=["meme", "dreme", "streme"], default="meme")
    parser.add_argument("--extra-args", nargs=argparse.REMAINDER, default=[], help="Additional arguments appended to the external command.")
    args = parser.parse_args(argv)

    print(" ".join(meme_command(args.fasta, args.outdir, method=args.method, extra_args=args.extra_args)))
    return 0


def motif_discovery_plan_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare or run a de novo motif discovery command plan.")
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--fasta", help="Existing candidate FASTA.")
    input_group.add_argument("--candidates", help="Candidate BED from call-footprints --output-bed or another BED-like source.")
    parser.add_argument("--genome", help="Genome FASTA, required when --candidates is used.")
    parser.add_argument("--flank", type=int, default=0, help="If >0 with --candidates, export +/- flank bp around each candidate center.")
    parser.add_argument("--outdir", required=True, help="External motif discovery output directory.")
    parser.add_argument("--script", help="Output shell script path. Defaults to <outdir>/run_motif_discovery.sh.")
    parser.add_argument("--method", choices=["meme", "dreme", "streme"], default="meme")
    parser.add_argument("--known-motifs", help="Optional known motif database for Tomtom comparison.")
    parser.add_argument("--extra-args", nargs=argparse.REMAINDER, default=[], help="Additional arguments appended to MEME/DREME/STREME.")
    parser.add_argument("--execute", action="store_true", help="Run the generated script immediately.")
    args = parser.parse_args(argv)

    outdir = Path(args.outdir)
    if args.candidates:
        if not args.genome:
            parser.error("--genome is required when --candidates is used")
        fasta = outdir / "candidate_sequences.fa"
        written = export_candidate_fasta(args.candidates, args.genome, fasta, flank=args.flank)
        if written == 0:
            raise SystemExit("No candidate sequences were exported; check candidate BED and genome FASTA.")
    else:
        fasta = Path(args.fasta)

    script = write_motif_discovery_plan(
        fasta,
        outdir,
        args.script or str(outdir / "run_motif_discovery.sh"),
        method=args.method,
        known_motifs=args.known_motifs,
        extra_args=args.extra_args,
    )
    print(script)
    if args.execute:
        subprocess.run([str(script)], check=True)
    return 0


def motif_report_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Summarize MEME/Tomtom outputs into TSV and HTML reports.")
    parser.add_argument("--meme-txt", help="MEME text output, usually meme.txt.")
    parser.add_argument("--tomtom-tsv", help="Tomtom TSV output, usually tomtom.tsv.")
    parser.add_argument("--out-tsv", required=True, help="Output motif summary TSV.")
    parser.add_argument("--out-html", help="Optional output HTML report.")
    parser.add_argument("--title", default="fp-tools de novo motif summary")
    args = parser.parse_args(argv)

    rows = summarize_motif_outputs(args.meme_txt, args.tomtom_tsv)
    if not rows:
        raise SystemExit("No motif rows were parsed; provide a valid MEME text or Tomtom TSV file.")
    write_motif_summary_tsv(rows, args.out_tsv)
    print(f"Wrote {len(rows)} motif rows to {args.out_tsv}")
    if args.out_html:
        write_motif_summary_html(rows, args.out_html, title=args.title)
        print(f"Wrote motif report to {args.out_html}")
    return 0


if __name__ == "__main__":
    raise SystemExit(export_fasta_main())
