#!/usr/bin/env python
"""Run a full pseudobulk ATAC footprint workflow from single-cell fragments or tagged BAMs."""

from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd

from fp_tools.tools.pseudobulk import _parse_chrom_list, _truthy, group_bam_by_tag, group_fragments
from fp_tools.utils.motif_databases import motif_db_table, resolve_motif_inputs


def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def _resolve_executable(name: str) -> str:
    local = Path(sys.executable).parent / name
    if local.exists():
        return str(local)
    found = shutil.which(name)
    return found or name


def _quote_command(command: list[str]) -> str:
    return " ".join(shlex.quote(str(part)) for part in command)


def _filter_bed_by_chroms(
    source: str | Path,
    output: str | Path,
    include_chroms: set[str] | None = None,
    exclude_chroms: set[str] | None = None,
) -> Path:
    source = Path(source)
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if include_chroms is None and exclude_chroms is None:
        return source

    kept = 0
    with source.open(encoding="utf-8") as src, output.open("w", encoding="utf-8") as dst:
        for line in src:
            if not line.strip() or line.startswith("#"):
                continue
            chrom = line.split("\t", 1)[0]
            if include_chroms is not None and chrom not in include_chroms:
                continue
            if exclude_chroms is not None and chrom in exclude_chroms:
                continue
            dst.write(line)
            kept += 1
    if kept == 0:
        raise ValueError(f"No peaks remained after chromosome filtering: {source}")
    return output


def _write_commands(commands: list[tuple[str, list[str]]], output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by pseudobulk-footprints.",
        "",
    ]
    for label, command in commands:
        lines.append(f"# {label}")
        lines.append(_quote_command(command))
        lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")
    output.chmod(0o755)
    return output


def _run_command(command: list[str], stdout_path: Path, stderr_path: Path) -> int:
    stdout_path.parent.mkdir(parents=True, exist_ok=True)
    resolved = list(command)
    resolved[0] = _resolve_executable(resolved[0])
    env = os.environ.copy()
    env.setdefault("MPLCONFIGDIR", str(stdout_path.parent / ".mplconfig"))
    env.setdefault("XDG_CACHE_HOME", str(stdout_path.parent / ".cache"))
    Path(env["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)
    Path(env["XDG_CACHE_HOME"]).mkdir(parents=True, exist_ok=True)
    with stdout_path.open("w", encoding="utf-8") as stdout, stderr_path.open("w", encoding="utf-8") as stderr:
        result = subprocess.run(resolved, stdout=stdout, stderr=stderr, text=True, env=env, check=False)
    return result.returncode


def _existing_ok(path: str | Path) -> bool:
    path = Path(path)
    return path.exists() and path.stat().st_size > 0


def _read_shift_from_row(args: argparse.Namespace, source: pd.Series) -> list[int]:
    if args.read_shift is not None:
        return [int(args.read_shift[0]), int(args.read_shift[1])]
    value = str(source.get("read_shift", "0 0")).strip() or "0 0"
    fields = value.split()
    if len(fields) != 2:
        return [0, 0]
    return [int(fields[0]), int(fields[1])]


def _group_inputs(args: argparse.Namespace, grouping_dir: Path, include_chroms: set[str] | None, exclude_chroms: set[str] | None) -> pd.DataFrame:
    if args.bam:
        return group_bam_by_tag(
            args.bam,
            args.annotations,
            grouping_dir,
            group_by=_split_csv(args.group_by),
            barcode_column=args.barcode_column,
            barcode_tag=args.bam_barcode_tag,
            min_cells=args.min_cells,
            min_fragments=args.min_fragments,
            strip_barcode_suffix=not args.no_strip_barcode_suffix,
            include_chroms=include_chroms,
            exclude_chroms=exclude_chroms,
            cores=args.cores,
        )

    manifest = group_fragments(
        args.fragments,
        args.annotations,
        grouping_dir,
        group_by=_split_csv(args.group_by),
        barcode_column=args.barcode_column,
        min_cells=args.min_cells,
        min_fragments=args.min_fragments,
        strip_barcode_suffix=not args.no_strip_barcode_suffix,
        include_chroms=include_chroms,
        exclude_chroms=exclude_chroms,
        compress_output=True,
        index_output=True,
        genome_sizes=args.genome_sizes,
        write_cutsite_bigwigs=True,
        write_pseudo_bams=True,
        cpm_normalize=not args.no_cpm_normalize,
        cores=args.cores,
    )
    manifest["source_type"] = "fragments"
    manifest["read_shift"] = "0 0"
    return manifest


def run_pseudobulk_footprints(args: argparse.Namespace) -> int:
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    grouping_dir = outdir / "pseudobulk"
    atac_dir = outdir / "atacorrect"
    footprint_dir = outdir / "footprints"
    plot_dir = outdir / "plots"
    bindetect_dir = outdir / "bindetect"
    log_dir = outdir / "logs"
    for path in (atac_dir, footprint_dir, plot_dir, bindetect_dir, log_dir):
        path.mkdir(parents=True, exist_ok=True)

    include_chroms = _parse_chrom_list(args.include_chroms)
    exclude_chroms = _parse_chrom_list(args.exclude_chroms)
    peaks_for_run = _filter_bed_by_chroms(
        args.peaks,
        outdir / "workflow_inputs" / "peaks.filtered.bed",
        include_chroms=include_chroms,
        exclude_chroms=exclude_chroms,
    )

    manifest = _group_inputs(args, grouping_dir, include_chroms, exclude_chroms)
    selected_groups = set(_split_csv(args.groups))
    rows = []
    commands: list[tuple[str, list[str]]] = []
    exit_code = 0

    for _, source in manifest.iterrows():
        group = str(source["group"])
        passes = _truthy(source.get("passes_filters", False))
        selected = not selected_groups or group in selected_groups
        row = source.to_dict()
        row.update(
            {
                "atacorrect_dir": "",
                "corrected_bigwig": "",
                "footprint_bigwig": "",
                "candidate_bed": "",
                "atacorrect_stdout": "",
                "atacorrect_stderr": "",
                "call_footprints_stdout": "",
                "call_footprints_stderr": "",
                "bindetect_outdir": "",
                "bindetect_results": "",
                "status": "filtered" if not passes else ("skipped_group" if not selected else "pending"),
            }
        )
        if not passes or not selected:
            rows.append(row)
            continue

        group_atac_dir = atac_dir / group
        corrected_bigwig = group_atac_dir / f"{group}_corrected.bw"
        footprint_bigwig = footprint_dir / f"{group}.footprints.bw"
        candidate_bed = footprint_dir / f"{group}.candidate_footprints.bed"
        atac_stdout = log_dir / f"{group}.atacorrect.stdout.log"
        atac_stderr = log_dir / f"{group}.atacorrect.stderr.log"
        fp_stdout = log_dir / f"{group}.call_footprints.stdout.log"
        fp_stderr = log_dir / f"{group}.call_footprints.stderr.log"
        read_shift = _read_shift_from_row(args, source)

        atac_command = [
            "atac-correct",
            "--bam",
            str(source["pseudo_bam"]),
            "--genome",
            str(args.genome),
            "--peaks",
            str(peaks_for_run),
            "--outdir",
            str(group_atac_dir),
            "--prefix",
            group,
            "--read_shift",
            str(read_shift[0]),
            str(read_shift[1]),
            "--cores",
            str(args.cores),
        ]
        if args.blacklist:
            atac_command.extend(["--blacklist", str(args.blacklist)])

        footprint_command = [
            "call-footprints",
            "--signal",
            str(corrected_bigwig),
            "--regions",
            str(peaks_for_run),
            "--output",
            str(footprint_bigwig),
            "--score",
            "footprint",
            "--output-bed",
            str(candidate_bed),
            "--cores",
            str(args.cores),
        ]
        if args.top_n:
            footprint_command.extend(["--top-n", str(args.top_n)])

        commands.append((f"{group}: ATACorrect", atac_command))
        commands.append((f"{group}: call-footprints", footprint_command))

        status = "dry_run"
        if not args.dry_run:
            status = "succeeded"
            if args.force or not (args.resume and _existing_ok(corrected_bigwig)):
                code = _run_command(atac_command, atac_stdout, atac_stderr)
                if code != 0:
                    status = "atacorrect_failed"
                    exit_code = code
            footprint_complete = _existing_ok(footprint_bigwig) and _existing_ok(candidate_bed)
            if status == "succeeded" and (args.force or not (args.resume and footprint_complete)):
                code = _run_command(footprint_command, fp_stdout, fp_stderr)
                if code != 0:
                    status = "call_footprints_failed"
                    exit_code = code

        row.update(
            {
                "atacorrect_dir": str(group_atac_dir),
                "corrected_bigwig": str(corrected_bigwig),
                "footprint_bigwig": str(footprint_bigwig),
                "candidate_bed": str(candidate_bed),
                "atacorrect_stdout": str(atac_stdout),
                "atacorrect_stderr": str(atac_stderr),
                "call_footprints_stdout": str(fp_stdout),
                "call_footprints_stderr": str(fp_stderr),
                "status": status,
            }
        )
        rows.append(row)
        if exit_code and args.fail_fast:
            break

    output_manifest = pd.DataFrame(rows)
    runnable_mask = output_manifest["status"].isin(["succeeded", "dry_run"])
    motif_inputs = resolve_motif_inputs(args.motifs, args.motif_db, use_default=False)
    if motif_inputs and runnable_mask.any():
        bindetect_results = bindetect_dir / f"{args.bindetect_prefix}_results.txt"
        output_manifest.loc[runnable_mask, "bindetect_outdir"] = str(bindetect_dir)
        output_manifest.loc[runnable_mask, "bindetect_results"] = str(bindetect_results)
        signal_rows = output_manifest.loc[runnable_mask]
        bindetect_command = [
            "diff-footprints",
            "--signals",
            *signal_rows["footprint_bigwig"].astype(str).tolist(),
            "--aggregate-signals",
            *signal_rows["corrected_bigwig"].astype(str).tolist(),
            "--cond-names",
            *signal_rows["group"].astype(str).tolist(),
            "--genome",
            str(args.genome),
            "--peaks",
            str(peaks_for_run),
            "--outdir",
            str(bindetect_dir),
            "--prefix",
            args.bindetect_prefix,
            "--normalization",
            args.bindetect_normalization,
            "--plot-aggregate",
            args.bindetect_plot_aggregate,
            "--cores",
            str(args.cores),
        ]
        if args.motif_db:
            bindetect_command.extend(["--motif-db", str(args.motif_db)])
        if args.motifs:
            bindetect_command.extend(["--motifs", *[str(path) for path in args.motifs]])
        if args.peak_header:
            bindetect_command.extend(["--peak-header", str(args.peak_header)])
        if args.skip_excel:
            bindetect_command.append("--skip-excel")
        commands.append(("motif-aware pseudobulk binding detection", bindetect_command))
        if not args.dry_run and exit_code == 0:
            code = _run_command(bindetect_command, log_dir / "bindetect.stdout.log", log_dir / "bindetect.stderr.log")
            if code != 0:
                exit_code = code

    manifest_path = outdir / "pseudobulk_footprint_manifest.tsv"
    output_manifest.to_csv(manifest_path, sep="\t", index=False)

    if args.tf_site_dir:
        plot_script = Path(args.plot_script)
        if not plot_script.exists():
            plot_script = Path.cwd() / args.plot_script
        plot_command = [
            sys.executable,
            str(plot_script),
            "--manifest",
            str(manifest_path),
            "--tf-site-dir",
            str(args.tf_site_dir),
            "--out-prefix",
            str(plot_dir / "pseudobulk_footprint_aggregate"),
            "--signal-column",
            "footprint_bigwig",
            "--value-column",
            "footprint_score",
            "--ylabel",
            "Footprint score",
            "--groups",
            args.groups or ",".join(output_manifest.loc[output_manifest["status"].isin(["succeeded", "dry_run"]), "group"].astype(str).tolist()),
            "--tfs",
            args.tfs,
            "--flank",
            str(args.plot_flank),
        ]
        if args.site_summary:
            plot_command.extend(["--site-summary", str(args.site_summary)])
        commands.append(("plot corrected pseudobulk footprints", plot_command))
        if not args.dry_run and exit_code == 0:
            code = _run_command(plot_command, log_dir / "plot_footprints.stdout.log", log_dir / "plot_footprints.stderr.log")
            if code != 0:
                exit_code = code

    command_path = _write_commands(commands, outdir / "pseudobulk_footprint_commands.sh")
    print(f"Wrote workflow manifest to {manifest_path}")
    print(f"Wrote command log to {command_path}")
    if args.dry_run:
        for label, command in commands:
            print(f"[{label}] {_quote_command(command)}")
    return exit_code


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--fragments", help="10x-style fragments TSV/TSV.GZ with barcode in column 4.")
    input_group.add_argument("--bam", help="All-cell BAM with cell barcodes stored in a read tag, e.g. CB.")
    parser.add_argument("--annotations", required=True, help="Cell annotation TSV or CSV.")
    parser.add_argument("--group-by", required=True, help="Comma-separated annotation columns to group by.")
    parser.add_argument("--outdir", required=True, help="Output directory for the full pseudobulk footprint workflow.")
    parser.add_argument("--genome-sizes", help="Two-column chromosome sizes file; required for fragment input cut-site bigWigs and pseudo-BAMs.")
    parser.add_argument("--genome", required=True, help="Genome FASTA for atac-correct.")
    parser.add_argument("--peaks", required=True, help="Peak BED used for ATACCorrect and footprint scoring.")
    parser.add_argument("--blacklist", help="Optional blacklist BED for atac-correct.")
    parser.add_argument("--barcode-column", default="barcode", help="Annotation barcode column (default: barcode).")
    parser.add_argument("--bam-barcode-tag", default="CB", help="BAM read tag containing cell barcodes for --bam input (default: CB).")
    parser.add_argument("--no-strip-barcode-suffix", action="store_true", help="Require exact barcode matches instead of matching AAAC-1 to AAAC.")
    parser.add_argument("--include-chroms", help="Comma-separated chromosomes to keep.")
    parser.add_argument("--exclude-chroms", help="Comma-separated chromosomes to skip.")
    parser.add_argument("--groups", default="", help="Comma-separated pseudobulk groups to process after grouping; default processes all retained groups.")
    parser.add_argument("--min-cells", type=int, default=1, help="Minimum cells for passes_filters (default: 1).")
    parser.add_argument("--min-fragments", type=int, default=1, help="Minimum fragments/reads for passes_filters (default: 1).")
    parser.add_argument("--no-cpm-normalize", action="store_true", help="Write raw cut counts instead of CPM-normalized cut-site bigWigs for fragment input.")
    parser.add_argument("--top-n", type=int, default=None, help="Optional top N candidate footprints per group.")
    parser.add_argument("--read-shift", nargs=2, type=int, metavar=("FWD", "REV"), help="Override ATACorrect read shift; default is 0 0 for fragment pseudo-BAMs and 4 -5 for tagged BAM input.")
    parser.add_argument("--motifs", nargs="*", help="Optional motif file(s); when provided, run motif-aware diff-footprints on pseudobulk footprint tracks.")
    parser.add_argument("--motif-db", help="Optional built-in motif database for motif-aware diff-footprints; can be combined with --motifs.")
    parser.add_argument("--list-motif-dbs", action="store_true", help="List available built-in motif databases and exit.")
    parser.add_argument("--peak-header", help="Optional peak-header file passed to diff-footprints.")
    parser.add_argument("--bindetect-prefix", default="pseudobulk_bindetect", help="Prefix for optional motif-aware diff-footprints outputs.")
    parser.add_argument("--bindetect-normalization", choices=["condition-quantile", "sample-quantile", "none"], default="none", help="Normalization mode for optional motif-aware diff-footprints outputs (default: none).")
    parser.add_argument("--bindetect-plot-aggregate", choices=["sig", "all", "top", "off"], default="top", help="Aggregate plot selection for optional motif-aware diff-footprints HTML/PDF outputs.")
    parser.add_argument("--skip-excel", action=argparse.BooleanOptionalAction, default=True, help="Skip Excel files for optional diff-footprints outputs (default: on).")
    parser.add_argument("--tf-site-dir", help="Optional motif-centered BED directory to plot corrected footprint aggregates.")
    parser.add_argument("--site-summary", help="Optional motif-centered site summary TSV for plotting.")
    parser.add_argument("--tfs", default="auto", help="Comma-separated TFs or 'auto' for plotting (default: auto).")
    parser.add_argument("--plot-flank", type=int, default=100, help="Flank for optional aggregate plots (default: 100).")
    parser.add_argument("--plot-script", default="manuscript/scripts/plot_pseudobulk_tf_aggregates.py", help="Plotting script path for optional aggregate plots.")
    parser.add_argument("--cores", type=int, default=1, help="Cores for grouping, ATACorrect, and footprint scoring (default: 1).")
    parser.add_argument("--resume", action="store_true", help="Skip ATACCorrect/call-footprints steps whose expected outputs already exist.")
    parser.add_argument("--force", action="store_true", help="Run ATACCorrect/call-footprints even if outputs already exist.")
    parser.add_argument("--dry-run", action="store_true", help="Write manifests and commands without running ATACCorrect, call-footprints, motif detection, or plots.")
    parser.add_argument("--fail-fast", action="store_true", help="Stop after the first failed group command.")
    return parser


def main(argv: list[str] | None = None) -> int:
    raw_args = sys.argv[1:] if argv is None else argv
    if "--list-motif-dbs" in raw_args:
        print(motif_db_table())
        return 0
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.force and args.resume:
        parser.error("--force and --resume are mutually exclusive")
    if args.fragments and not args.genome_sizes:
        parser.error("--genome-sizes is required with --fragments")
    return run_pseudobulk_footprints(args)


if __name__ == "__main__":
    raise SystemExit(main())
