#!/usr/bin/env python
"""Pseudobulk fragment grouping utility."""

from __future__ import annotations

import argparse
import gzip
import shlex
from collections import defaultdict
from pathlib import Path

import pandas as pd
import yaml


def _open_text(path: str | Path):
    path = Path(path)
    return gzip.open(path, "rt", encoding="utf-8") if path.suffix == ".gz" else path.open(encoding="utf-8")


def load_annotations(path: str | Path, barcode_column: str, group_by: list[str]) -> dict[str, str]:
    """Map barcodes to pseudobulk group labels."""

    frame = pd.read_csv(path, sep="\t")
    missing = [column for column in [barcode_column, *group_by] if column not in frame.columns]
    if missing:
        raise ValueError(f"Missing annotation columns: {missing}")
    mapping = {}
    for _, row in frame.iterrows():
        group = "__".join(str(row[column]) for column in group_by)
        mapping[str(row[barcode_column])] = group
    return mapping


def group_fragments(
    fragments: str | Path,
    annotations: str | Path,
    outdir: str | Path,
    group_by: list[str],
    barcode_column: str = "barcode",
    min_cells: int = 1,
    min_fragments: int = 1,
) -> pd.DataFrame:
    """Split fragments into pseudobulk group files and write a manifest/QC table."""

    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    barcode_to_group = load_annotations(annotations, barcode_column, group_by)
    handles = {}
    cells_by_group: dict[str, set[str]] = defaultdict(set)
    fragments_by_group: dict[str, int] = defaultdict(int)
    paths_by_group: dict[str, Path] = {}

    try:
        with _open_text(fragments) as handle:
            for line in handle:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.rstrip("\n").split("\t")
                if len(fields) < 4:
                    continue
                barcode = fields[3]
                group = barcode_to_group.get(barcode)
                if group is None:
                    continue
                if group not in handles:
                    path = outdir / f"{group}.fragments.tsv"
                    paths_by_group[group] = path
                    handles[group] = path.open("w", encoding="utf-8")
                handles[group].write(line)
                cells_by_group[group].add(barcode)
                count = int(fields[4]) if len(fields) > 4 and fields[4].isdigit() else 1
                fragments_by_group[group] += count
    finally:
        for handle in handles.values():
            handle.close()

    rows = []
    for group in sorted(paths_by_group):
        cells = len(cells_by_group[group])
        fragments_count = fragments_by_group[group]
        keep = cells >= min_cells and fragments_count >= min_fragments
        rows.append(
            {
                "group": group,
                "fragment_file": str(paths_by_group[group]),
                "n_cells": cells,
                "n_fragments": fragments_count,
                "passes_filters": keep,
            }
        )
    manifest = pd.DataFrame(rows)
    manifest_path = outdir / "pseudobulk_manifest.tsv"
    manifest.to_csv(manifest_path, sep="\t", index=False)

    config = {
        "version": 1,
        "pseudobulk_manifest": str(manifest_path),
        "group_by": group_by,
        "samples": [row for row in manifest.to_dict(orient="records") if row["passes_filters"]],
    }
    with (outdir / "fp_tools_manifest.yml").open("w", encoding="utf-8") as handle:
        yaml.safe_dump(config, handle, sort_keys=False)
    return manifest



def write_downstream_commands(
    manifest: pd.DataFrame,
    output: str | Path,
    genome_sizes: str | Path | None = None,
    cores: int = 1,
) -> Path:
    """Write a reproducible shell plan for pseudobulk BAM/bigWig generation."""

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    cores = max(1, int(cores))
    genome_arg = shlex.quote(str(genome_sizes)) if genome_sizes else "GENOME_SIZES.txt"
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by fp-tools-pseudobulk. Review paths and install bedtools, samtools, and bedGraphToBigWig before running.",
    ]
    if genome_sizes is None:
        lines.append("# Replace GENOME_SIZES.txt with a two-column chromosome sizes file before running bigWig/BAM steps.")
    lines.append("")

    runnable = manifest[manifest["passes_filters"].astype(bool)] if "passes_filters" in manifest.columns else manifest
    for _, row in runnable.iterrows():
        group = str(row["group"])
        fragment_file = Path(str(row["fragment_file"]))
        prefix = fragment_file.with_suffix("")
        bed = prefix.with_suffix(".bed")
        bedgraph = prefix.with_suffix(".bedGraph")
        unsorted_bam = prefix.with_suffix(".bam")
        sorted_bam = prefix.with_suffix(".sorted.bam")
        bigwig = prefix.with_suffix(".bw")
        lines.extend(
            [
                f"# {group}",
                f"awk 'BEGIN{{OFS=\"\\t\"}} !/^#/ {{print $1,$2,$3}}' {shlex.quote(str(fragment_file))} | sort -k1,1 -k2,2n > {shlex.quote(str(bed))}",
                f"bedtools genomecov -bg -i {shlex.quote(str(bed))} -g {genome_arg} > {shlex.quote(str(bedgraph))}",
                f"bedGraphToBigWig {shlex.quote(str(bedgraph))} {genome_arg} {shlex.quote(str(bigwig))}",
                f"bedToBam -i {shlex.quote(str(bed))} -g {genome_arg} > {shlex.quote(str(unsorted_bam))}",
                f"samtools sort -@ {cores} -o {shlex.quote(str(sorted_bam))} {shlex.quote(str(unsorted_bam))}",
                f"samtools index -@ {cores} {shlex.quote(str(sorted_bam))}",
                "",
            ]
        )
    output.write_text("\n".join(lines), encoding="utf-8")
    output.chmod(0o755)
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Group single-cell ATAC fragments into pseudobulk fragment files.")
    parser.add_argument("--fragments", required=True, help="10x-style fragments TSV/TSV.GZ with barcode in column 4.")
    parser.add_argument("--annotations", required=True, help="Cell annotation TSV.")
    parser.add_argument("--group-by", required=True, help="Comma-separated annotation columns to group by, e.g. donor,cell_type.")
    parser.add_argument("--barcode-column", default="barcode", help="Annotation barcode column (default: barcode).")
    parser.add_argument("--min-cells", type=int, default=1, help="Minimum cells for passes_filters (default: 1).")
    parser.add_argument("--min-fragments", type=int, default=1, help="Minimum fragments for passes_filters (default: 1).")
    parser.add_argument("--outdir", required=True, help="Output directory.")
    parser.add_argument("--write-downstream-commands", action="store_true", help="Write a shell script for BED/BAM/bigWig generation from kept pseudobulk groups.")
    parser.add_argument("--genome-sizes", help="Two-column chromosome sizes file used by generated bedtools/UCSC commands.")
    parser.add_argument("--cores", type=int, default=1, help="Cores to place in generated samtools sort/index commands.")
    args = parser.parse_args(argv)

    manifest = group_fragments(
        args.fragments,
        args.annotations,
        args.outdir,
        group_by=[column.strip() for column in args.group_by.split(",") if column.strip()],
        barcode_column=args.barcode_column,
        min_cells=args.min_cells,
        min_fragments=args.min_fragments,
    )
    print(f"Wrote {len(manifest)} pseudobulk groups to {args.outdir}")
    if args.write_downstream_commands:
        command_path = write_downstream_commands(
            manifest,
            Path(args.outdir) / "pseudobulk_downstream_commands.sh",
            genome_sizes=args.genome_sizes,
            cores=args.cores,
        )
        print(f"Wrote downstream command plan to {command_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
